plugins {
    id 'com.android.application'
}

android {
    namespace 'group.beto.grexnexus.child.pkgplaceholder00000'
    compileSdk 34

    defaultConfig {
        applicationId "group.beto.grexnexus.child.pkgplaceholder00000"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
        }
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    androidResources {
        noCompress 'js', 'html', 'css', 'json', 'wasm'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
